// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vendopasteles.backend.Contexts;

namespace vendopasteles.backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211107235153_creacion de la db, tablas y relaciones (ApplicationDbContext)")]
    partial class creaciondeladbtablasyrelacionesApplicationDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("vendopasteles.backend.Entities.Movimiento", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadProducto")
                        .HasColumnType("int");

                    b.Property<int>("CodigoMovimiento")
                        .HasColumnType("int");

                    b.Property<string>("FechaMovimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("CodigoMovimiento")
                        .IsUnique();

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("vendopasteles.backend.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadProducto")
                        .HasColumnType("int");

                    b.Property<int>("CodigoProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdMovimiento")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrecioProducto")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.HasIndex("CodigoProducto")
                        .IsUnique();

                    b.HasIndex("IdMovimiento");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("vendopasteles.backend.Entities.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DireccionProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdMovimiento")
                        .HasColumnType("int");

                    b.Property<int>("NitProveedor")
                        .HasColumnType("int");

                    b.Property<string>("NombreProveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelefonoProveedor")
                        .HasColumnType("int");

                    b.HasKey("IdProveedor");

                    b.HasIndex("IdMovimiento");

                    b.HasIndex("NitProveedor")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("vendopasteles.backend.Entities.Producto", b =>
                {
                    b.HasOne("vendopasteles.backend.Entities.Movimiento", "IdMovimientoNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdMovimiento")
                        .HasConstraintName("FK_IdMovimiento_Producto")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdMovimientoNavigation");
                });

            modelBuilder.Entity("vendopasteles.backend.Entities.Proveedor", b =>
                {
                    b.HasOne("vendopasteles.backend.Entities.Movimiento", "IdMovimientoNavigation")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdMovimiento")
                        .HasConstraintName("FK_IdMovimiento_Proveedor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("IdMovimientoNavigation");
                });

            modelBuilder.Entity("vendopasteles.backend.Entities.Movimiento", b =>
                {
                    b.Navigation("Productos");

                    b.Navigation("Proveedores");
                });
#pragma warning restore 612, 618
        }
    }
}
